server:
  port: 8080
  max-http-header-size: 64KB
  error:
    include-message: always
spring:
  application:
    name: web-server
  r2dbc:
    url: r2dbc:h2:file:///./data/h2db/jetlinks
    username: sa
    password:
    pool:
      max-size: 32
jetlinks:
  api:
    client:
      config:
        client-api-path: http://127.0.0.1:8080  #当前服务-接口地址
        server-api-path: http://127.0.0.1:9000/api #用户中台-接口地址
        client-id: client-id #应用ID
        client-secret: client-secret #应用密钥
        redirect-uri: http://127.0.0.1:8080 # 授权后的重定向地址
        authorization-url: http://127.0.0.1:9000/#/oauth
      menu:
        - id: sdk
          owner: sdk  #外部菜单所属应用ID
          name: sdk示例
          code: sdk-view  #编码。编码需在系统内唯一
          url: /sdk
          accessSupport: unsupported  #数据权限控制
        - id: device
          parentId: sdk
          owner: sdk  #外部菜单所属应用ID
          name: 设备管理
          code: sdk-device  #编码。编码需在系统内唯一
          url: /device.html
          permissions:  #绑定权限信息
            - permission: device  #权限ID
              name: 设备管理
              actions:  #支持的权限操作
                - query
          accessSupport: support  #数据权限控制
          assetType: device  #关联资产类型,accessSupport为support有值
          indirectMenus:  #关联菜单,accessSupport为indirect时不能为空
          buttons:  #按钮定义信息
            - id: view
              name: 查看
              permissions: #权限信息
                - permission: device  #权限ID
                  name: 设备管理
                  actions:  #支持的权限操作
                    - query
            - id: add
              name: 新增
              permissions:
                - permission: device
                  name: 设备管理
                  actions:
                    - save
            - id: update
              name: 编辑
              permissions:
                - permission: device
                  name: 设备管理
                  actions:
                    - update
            - id: delete
              name: 删除
              permissions:
                - permission: device
                  name: 设备管理
                  actions:
                    - delete
        - id: user
          parentId: sdk
          owner: sdk  #外部菜单所属应用ID
          name: 用户中心
          code: sdk-user  #编码。编码需在系统内唯一
          url: /user.html
          permissions: #绑定权限信息
            - permission: user  #权限ID
              name: 用户中心
              actions: #支持的权限操作
                - query
          accessSupport: support  #数据权限控制
          assetType: user  #关联资产类型,accessSupport为support有值
          indirectMenus:  #关联菜单,accessSupport为indirect时不能为空
          buttons: #按钮定义信息
            - id: view
              name: 查看
              permissions: #权限信息
                - permission: user  #权限ID
                  name: 用户中心
                  actions: #支持的权限操作
                    - query
            - id: update
              name: 编辑
              permissions:
                - permission: user
                  name: 用户中心
                  actions:
                    - update